# Generated by Django 6.0.1 on 2026-01-17 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_condition_ok', models.BooleanField(default=True)),
                ('tyre_condition_ok', models.BooleanField(default=True)),
                ('fire_extinguisher_available', models.BooleanField(default=True)),
                ('seal_no_before', models.CharField(blank=True, max_length=50)),
                ('seal_no_after', models.CharField(blank=True, max_length=50)),
                ('alcohol_test_done', models.BooleanField(default=False)),
                ('alcohol_test_passed', models.BooleanField(default=True)),
                ('inspected_by_name', models.CharField(max_length=100)),
                ('inspection_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
