# Generated by Django 6.0.1 on 2026-01-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security_checks', '0001_initial'),
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycheck',
            name='vehicle_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_check', to='vehicle_management.vehicleentry'),
        ),
    ]
