class NotificationTypeCode:
    """Constants for notification type codes."""

    # Person Gate Events
    PERSON_ENTRY = "PERSON_ENTRY"
    PERSON_EXIT = "PERSON_EXIT"
    LONG_DURATION_ALERT = "LONG_DURATION_ALERT"
    BLACKLISTED_PERSON = "BLACKLISTED_PERSON"

    # Vehicle Gate Events
    VEHICLE_ENTRY = "VEHICLE_ENTRY"
    VEHICLE_EXIT = "VEHICLE_EXIT"

    # Material Gate Events
    RAW_MATERIAL_GATEIN = "RAW_MATERIAL_GATEIN"
    DAILY_NEEDS_GATEIN = "DAILY_NEEDS_GATEIN"
    MAINTENANCE_GATEIN = "MAINTENANCE_GATEIN"
    CONSTRUCTION_GATEIN = "CONSTRUCTION_GATEIN"

    # QC Events
    QC_PENDING = "QC_PENDING"
    QC_COMPLETED = "QC_COMPLETED"
    QC_FAILED = "QC_FAILED"

    # Weighment Events
    WEIGHMENT_COMPLETED = "WEIGHMENT_COMPLETED"

    # Security Alerts
    SECURITY_ALERT = "SECURITY_ALERT"
