# Generated by Django 6.0.1 on 2026-01-28 10:05

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_management', '0004_vehicleentry_entry_type_alter_vehicleentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Construction Material Category',
                'verbose_name_plural': 'Construction Material Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionGateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('work_order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contractor_name', models.CharField(max_length=200)),
                ('contractor_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('material_description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Quantity must be positive')])),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LTR', 'Litre'), ('BOX', 'Box')], max_length=10)),
                ('challan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('site_engineer', models.CharField(blank=True, max_length=100, null=True)),
                ('security_approval', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inward_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_entries', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='construction_entry', to='driver_management.vehicleentry')),
                ('material_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_entries', to='construction_gatein.constructionmaterialcategory')),
            ],
            options={
                'verbose_name': 'Construction Gate Entry',
                'verbose_name_plural': 'Construction Gate Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material_category'], name='constructio_materia_63f89e_idx'), models.Index(fields=['security_approval'], name='constructio_securit_db420d_idx'), models.Index(fields=['created_at'], name='constructio_created_321a72_idx'), models.Index(fields=['work_order_number'], name='constructio_work_or_db9704_idx')],
            },
        ),
    ]
