# Generated by Django 6.0.1 on 2026-01-28 10:05

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Seed initial construction material categories"""
    ConstructionMaterialCategory = apps.get_model('construction_gatein', 'ConstructionMaterialCategory')

    categories = [
        {"category_name": "Cement", "description": "Portland cement, white cement, and other cement types"},
        {"category_name": "Steel/Rebar", "description": "Reinforcement bars, steel rods, and structural steel"},
        {"category_name": "Bricks/Blocks", "description": "Clay bricks, concrete blocks, and AAC blocks"},
        {"category_name": "Sand", "description": "River sand, M-sand, and construction sand"},
        {"category_name": "Aggregate/Gravel", "description": "Crushed stone, gravel, and coarse aggregate"},
        {"category_name": "Pipes/Fittings", "description": "PVC pipes, GI pipes, fittings, and plumbing materials"},
        {"category_name": "Electrical Materials", "description": "Wires, cables, switches, and electrical fittings"},
        {"category_name": "Tiles/Flooring", "description": "Ceramic tiles, vitrified tiles, and flooring materials"},
        {"category_name": "Paint/Finishing", "description": "Paints, primers, putty, and finishing materials"},
        {"category_name": "Wood/Timber", "description": "Timber, plywood, and wooden materials"},
        {"category_name": "Other", "description": "Other construction materials not categorized above"},
    ]

    for cat in categories:
        ConstructionMaterialCategory.objects.get_or_create(
            category_name=cat["category_name"],
            defaults={"description": cat["description"], "is_active": True}
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded categories"""
    ConstructionMaterialCategory = apps.get_model('construction_gatein', 'ConstructionMaterialCategory')
    category_names = [
        "Cement", "Steel/Rebar", "Bricks/Blocks", "Sand", "Aggregate/Gravel",
        "Pipes/Fittings", "Electrical Materials", "Tiles/Flooring",
        "Paint/Finishing", "Wood/Timber", "Other"
    ]
    ConstructionMaterialCategory.objects.filter(category_name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
