# Generated by Django 6.0.1 on 2026-01-30 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0002_seed_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiongateentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Quantity must be positive')]),
        ),
    ]
