# Generated by Django 6.0.1 on 2026-02-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0003_alter_constructiongateentry_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructiongateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_construction_entry', 'Can create construction gate entry'), ('can_view_construction_entry', 'Can view construction gate entry'), ('can_edit_construction_entry', 'Can edit construction gate entry'), ('can_delete_construction_entry', 'Can delete construction gate entry'), ('can_complete_construction_entry', 'Can complete construction gate entry')], 'verbose_name': 'Construction Gate Entry', 'verbose_name_plural': 'Construction Gate Entries'},
        ),
        migrations.AlterModelOptions(
            name='constructionmaterialcategory',
            options={'ordering': ['category_name'], 'permissions': [('can_view_material_category', 'Can view material category'), ('can_manage_material_category', 'Can manage material category')], 'verbose_name': 'Construction Material Category', 'verbose_name_plural': 'Construction Material Categories'},
        ),
    ]
