# Generated by Django 6.0.1 on 2026-02-06 10:49

from django.db import migrations


def create_construction_gatein_group(apps, schema_editor):
    """Create 'construction_gatein' group with all construction_gatein app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='construction_gatein')

    permissions = Permission.objects.filter(
        content_type__app_label='construction_gatein'
    )
    group.permissions.set(permissions)


def remove_construction_gatein_group(apps, schema_editor):
    """Remove 'construction_gatein' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='construction_gatein').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0004_add_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(create_construction_gatein_group, remove_construction_gatein_group),
    ]
