# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0005_create_construction_gatein_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructiongateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_complete_construction_entry', 'Can complete construction gate entry')], 'verbose_name': 'Construction Gate Entry', 'verbose_name_plural': 'Construction Gate Entries'},
        ),
        migrations.AlterModelOptions(
            name='constructionmaterialcategory',
            options={'ordering': ['category_name'], 'permissions': [('can_manage_material_category', 'Can manage material category')], 'verbose_name': 'Construction Material Category', 'verbose_name_plural': 'Construction Material Categories'},
        ),
    ]
