# Generated by Django 6.0.1 on 2026-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0008_cleanup_stale_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructiongateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_complete_construction_entry', 'Can complete construction gate entry')]},
        ),
        migrations.AlterModelOptions(
            name='constructionmaterialcategory',
            options={'ordering': ['category_name'], 'permissions': [('can_manage_material_category', 'Can manage material category')]},
        ),
    ]
