# Generated by Django 6.0.1 on 2026-01-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vehicleentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicleentry',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehicleentry',
            name='vehicle',
        ),
    ]
