# Generated by Django 6.0.1 on 2026-01-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0003_alter_poreceipt_vehicle_entry'),
        ('security_checks', '0003_alter_securitycheck_vehicle_entry'),
        ('vehicle_management', '0002_remove_vehicleentry_company_and_more'),
        ('weighment', '0002_alter_weighment_vehicle_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleEntry',
        ),
    ]
