# Generated by Django 6.0.1 on 2026-01-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0003_delete_vehicleentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
