# Generated by Django 6.0.1 on 2026-01-28 06:15

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_department'),
        ('driver_management', '0004_vehicleentry_entry_type_alter_vehicleentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maintenance Type',
                'verbose_name_plural': 'Maintenance Types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceGateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('material_description', models.TextField()),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Quantity must be positive')])),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LTR', 'Litre'), ('BOX', 'Box')], max_length=10)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_id', models.CharField(blank=True, help_text='Equipment/Machine ID for the repair/maintenance', max_length=100, null=True)),
                ('urgency_level', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('inward_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to=settings.AUTH_USER_MODEL)),
                ('receiving_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to='accounts.department')),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_entry', to='driver_management.vehicleentry')),
                ('maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to='maintenance_gatein.maintenancetype')),
            ],
            options={
                'verbose_name': 'Maintenance Gate Entry',
                'verbose_name_plural': 'Maintenance Gate Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['maintenance_type'], name='maintenance_mainten_2ec9ab_idx'), models.Index(fields=['urgency_level'], name='maintenance_urgency_b3c10b_idx'), models.Index(fields=['created_at'], name='maintenance_created_e9396d_idx'), models.Index(fields=['work_order_number'], name='maintenance_work_or_873776_idx')],
            },
        ),
    ]
