# Generated by Django 6.0.1 on 2026-02-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_gatein', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancegateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_maintenance_entry', 'Can create maintenance gate entry'), ('can_view_maintenance_entry', 'Can view maintenance gate entry'), ('can_edit_maintenance_entry', 'Can edit maintenance gate entry'), ('can_delete_maintenance_entry', 'Can delete maintenance gate entry'), ('can_complete_maintenance_entry', 'Can complete maintenance gate entry')], 'verbose_name': 'Maintenance Gate Entry', 'verbose_name_plural': 'Maintenance Gate Entries'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'ordering': ['type_name'], 'permissions': [('can_view_maintenance_type', 'Can view maintenance type'), ('can_manage_maintenance_type', 'Can manage maintenance type')], 'verbose_name': 'Maintenance Type', 'verbose_name_plural': 'Maintenance Types'},
        ),
    ]
