# Generated by Django 6.0.1 on 2026-02-06 11:07

from django.db import migrations


def create_maintenance_gatein_group(apps, schema_editor):
    """Create 'maintenance_gatein' group with all maintenance_gatein app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='maintenance_gatein')

    permissions = Permission.objects.filter(
        content_type__app_label='maintenance_gatein'
    )
    group.permissions.set(permissions)


def remove_maintenance_gatein_group(apps, schema_editor):
    """Remove 'maintenance_gatein' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='maintenance_gatein').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_gatein', '0002_add_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(create_maintenance_gatein_group, remove_maintenance_gatein_group),
    ]
