# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_gatein', '0003_create_maintenance_gatein_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancegateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_complete_maintenance_entry', 'Can complete maintenance gate entry')], 'verbose_name': 'Maintenance Gate Entry', 'verbose_name_plural': 'Maintenance Gate Entries'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'ordering': ['type_name'], 'permissions': [('can_manage_maintenance_type', 'Can manage maintenance type')], 'verbose_name': 'Maintenance Type', 'verbose_name_plural': 'Maintenance Types'},
        ),
    ]
