# Generated by Django 6.0.1 on 2026-02-06 12:50

from django.db import migrations

STALE_PERMISSIONS = [
    "can_create_maintenance_entry",
    "can_view_maintenance_entry",
    "can_edit_maintenance_entry",
    "can_delete_maintenance_entry",
    "can_view_maintenance_type",
]


def cleanup_stale_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        content_type__app_label='maintenance_gatein',
        codename__in=STALE_PERMISSIONS,
    ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_gatein', '0005_update_maintenance_gatein_group'),
    ]

    operations = [
        migrations.RunPython(cleanup_stale_permissions, noop),
    ]
