# Generated by Django 6.0.1 on 2026-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_gatein', '0006_cleanup_stale_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancegateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_complete_maintenance_entry', 'Can complete maintenance gate entry')]},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'ordering': ['type_name'], 'permissions': [('can_manage_maintenance_type', 'Can manage maintenance type')]},
        ),
    ]
