# Generated by Django 6.0.1 on 2026-02-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0004_remove_unitchoice_created_at_and_more'),
        ('maintenance_gatein', '0007_alter_maintenancegateentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancegateentry',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to='gate_core.unitchoice'),
        ),
    ]
