# Generated by Django 6.0.1 on 2026-02-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_management', '0005_increase_status_max_length'),
        ('raw_material_gatein', '0003_alter_poreceipt_vehicle_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRPOPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_doc_entry', models.IntegerField(blank=True, help_text='SAP DocEntry', null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, help_text='SAP DocNum', null=True)),
                ('sap_doc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('PARTIALLY_POSTED', 'Partially Posted')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grpo_postings', to='raw_material_gatein.poreceipt')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grpo_postings', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grpo_postings', to='driver_management.vehicleentry')),
            ],
            options={
                'verbose_name': 'GRPO Posting',
                'verbose_name_plural': 'GRPO Postings',
                'ordering': ['-created_at'],
                'unique_together': {('vehicle_entry', 'po_receipt')},
            },
        ),
        migrations.CreateModel(
            name='GRPOLinePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_posted', models.DecimalField(decimal_places=3, max_digits=12)),
                ('base_entry', models.IntegerField(blank=True, help_text='PO DocEntry in SAP', null=True)),
                ('base_line', models.IntegerField(blank=True, help_text='PO Line Number in SAP', null=True)),
                ('po_item_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grpo_lines', to='raw_material_gatein.poitemreceipt')),
                ('grpo_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='grpo.grpoposting')),
            ],
            options={
                'verbose_name': 'GRPO Line Posting',
                'verbose_name_plural': 'GRPO Line Postings',
            },
        ),
    ]
