# Generated by Django 6.0.1 on 2026-02-06 11:19

from django.db import migrations


def create_grpo_group(apps, schema_editor):
    """Create 'grpo' group with all grpo app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='grpo')

    permissions = Permission.objects.filter(
        content_type__app_label='grpo'
    )
    group.permissions.set(permissions)


def remove_grpo_group(apps, schema_editor):
    """Remove 'grpo' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='grpo').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0002_alter_grpoposting_options'),
    ]

    operations = [
        migrations.RunPython(create_grpo_group, remove_grpo_group),
    ]
