# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0003_create_grpo_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grpoposting',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_pending_grpo', 'Can view pending GRPO entries'), ('can_preview_grpo', 'Can preview GRPO data'), ('can_view_grpo_history', 'Can view GRPO posting history')], 'verbose_name': 'GRPO Posting', 'verbose_name_plural': 'GRPO Postings'},
        ),
    ]
