# Generated by Django 6.0.1 on 2026-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0006_cleanup_stale_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grpolineposting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grpoposting',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_pending_grpo', 'Can view pending grpo entries'), ('can_preview_grpo', 'Can preview grpo data'), ('can_view_grpo_history', 'Can view GRPO posting history')]},
        ),
    ]
