# Generated by Django 6.0.1 on 2026-02-28 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0007_alter_grpolineposting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRPOAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='grpo_attachments/')),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('sap_attachment_status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded to SAP'), ('LINKED', 'Linked to GRPO Document'), ('FAILED', 'Upload Failed')], default='PENDING', max_length=20)),
                ('sap_absolute_entry', models.IntegerField(blank=True, help_text='SAP Attachments2 AbsoluteEntry after upload', null=True)),
                ('sap_error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grpo_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grpo.grpoposting')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grpo_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
