# Generated by Django 6.0.1 on 2026-02-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_view_department', 'Can view department'), ('can_manage_department', 'Can manage department')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_user', 'Can create user'), ('can_view_user', 'Can view user'), ('can_edit_user', 'Can edit user'), ('can_delete_user', 'Can delete user'), ('can_manage_user_permissions', 'Can manage user permissions')]},
        ),
    ]
