# Generated by Django 6.0.1 on 2026-02-06 07:09

from django.db import migrations


def create_account_group(apps, schema_editor):
    """Create 'account' group with all account app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Create or get the account group
    group, created = Group.objects.get_or_create(name='account')

    # Get all permissions for accounts app
    account_permissions = Permission.objects.filter(
        content_type__app_label='accounts'
    )

    # Add all permissions to the group
    group.permissions.set(account_permissions)


def remove_account_group(apps, schema_editor):
    """Remove 'account' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='account').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(create_account_group, remove_account_group),
    ]
