# Generated by Django 6.0.1 on 2026-02-06 12:50

from django.db import migrations

STALE_PERMISSIONS = [
    "can_create_user",
    "can_view_user",
    "can_edit_user",
    "can_delete_user",
    "can_view_department",
]


def cleanup_stale_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        content_type__app_label='accounts',
        codename__in=STALE_PERMISSIONS,
    ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_department_options_alter_user_options'),
    ]

    operations = [
        migrations.RunPython(cleanup_stale_permissions, noop),
    ]
