# Generated by Django 6.0.1 on 2026-02-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_gatein', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'permissions': [('can_create_contractor', 'Can create contractor'), ('can_view_contractor', 'Can view contractor'), ('can_edit_contractor', 'Can edit contractor'), ('can_delete_contractor', 'Can delete contractor')]},
        ),
        migrations.AlterModelOptions(
            name='entrylog',
            options={'permissions': [('can_create_entry', 'Can create person gate entry'), ('can_view_entry', 'Can view person gate entry'), ('can_edit_entry', 'Can edit person gate entry'), ('can_delete_entry', 'Can delete person gate entry'), ('can_cancel_entry', 'Can cancel person gate entry'), ('can_exit_entry', 'Can mark person gate exit'), ('can_search_entry', 'Can search person gate entries'), ('can_view_dashboard', 'Can view person gate dashboard')]},
        ),
        migrations.AlterModelOptions(
            name='gate',
            options={'permissions': [('can_view_gate', 'Can view gate'), ('can_manage_gate', 'Can manage gate')]},
        ),
        migrations.AlterModelOptions(
            name='labour',
            options={'permissions': [('can_create_labour', 'Can create labour'), ('can_view_labour', 'Can view labour'), ('can_edit_labour', 'Can edit labour'), ('can_delete_labour', 'Can delete labour')]},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'permissions': [('can_view_person_type', 'Can view person type'), ('can_manage_person_type', 'Can manage person type')]},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'permissions': [('can_create_visitor', 'Can create visitor'), ('can_view_visitor', 'Can view visitor'), ('can_edit_visitor', 'Can edit visitor'), ('can_delete_visitor', 'Can delete visitor')]},
        ),
    ]
