# Generated by Django 6.0.1 on 2026-02-06 11:15

from django.db import migrations


def create_person_gatein_group(apps, schema_editor):
    """Create 'person_gatein' group with all person_gatein app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='person_gatein')

    permissions = Permission.objects.filter(
        content_type__app_label='person_gatein'
    )
    group.permissions.set(permissions)


def remove_person_gatein_group(apps, schema_editor):
    """Remove 'person_gatein' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='person_gatein').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('person_gatein', '0002_alter_contractor_options_alter_entrylog_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_person_gatein_group, remove_person_gatein_group),
    ]
