# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_gatein', '0003_create_person_gatein_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entrylog',
            options={'permissions': [('can_cancel_entry', 'Can cancel person gate entry'), ('can_exit_entry', 'Can mark person gate exit'), ('can_search_entry', 'Can search person gate entries'), ('can_view_dashboard', 'Can view person gate dashboard')]},
        ),
        migrations.AlterModelOptions(
            name='gate',
            options={'permissions': [('can_manage_gate', 'Can manage gate')]},
        ),
        migrations.AlterModelOptions(
            name='labour',
            options={},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'permissions': [('can_manage_person_type', 'Can manage person type')]},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={},
        ),
    ]
