# Generated by Django 6.0.1 on 2026-02-06 12:50

from django.db import migrations

STALE_PERMISSIONS = [
    "can_create_contractor",
    "can_view_contractor",
    "can_edit_contractor",
    "can_delete_contractor",
    "can_create_visitor",
    "can_view_visitor",
    "can_edit_visitor",
    "can_delete_visitor",
    "can_create_labour",
    "can_view_labour",
    "can_edit_labour",
    "can_delete_labour",
    "can_create_entry",
    "can_view_entry",
    "can_edit_entry",
    "can_delete_entry",
    "can_view_person_type",
    "can_view_gate",
]


def cleanup_stale_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        content_type__app_label='person_gatein',
        codename__in=STALE_PERMISSIONS,
    ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('person_gatein', '0005_update_person_gatein_group'),
    ]

    operations = [
        migrations.RunPython(cleanup_stale_permissions, noop),
    ]
