# Generated by Django 6.0.1 on 2026-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_gatein', '0006_cleanup_stale_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='actual_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
