# Generated by Django 6.0.1 on 2026-01-17 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_control', '0001_initial'),
        ('raw_material_gatein', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='po_item_receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspection', to='raw_material_gatein.poitemreceipt'),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
