# Generated by Django 6.0.1 on 2026-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_alter_qcinspection_inspected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinspection',
            name='inspected_by',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
