# Generated by Django 6.0.1 on 2026-01-19 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0004_alter_qcinspection_inspected_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinspection',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_inspections', to=settings.AUTH_USER_MODEL),
        ),
    ]
