# Generated by Django 6.0.1 on 2026-02-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0006_new_quality_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialarrivalslip',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_arrival_slip', 'Can create material arrival slip'), ('can_edit_arrival_slip', 'Can edit material arrival slip'), ('can_submit_arrival_slip', 'Can submit arrival slip to QA'), ('can_view_arrival_slip', 'Can view material arrival slip')]},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name'], 'permissions': [('can_manage_material_types', 'Can manage material types'), ('can_manage_qc_parameters', 'Can manage QC parameters')]},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinspection',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_inspection', 'Can create raw material inspection'), ('can_edit_inspection', 'Can edit raw material inspection'), ('can_submit_inspection', 'Can submit inspection for approval'), ('can_view_inspection', 'Can view raw material inspection'), ('can_approve_as_chemist', 'Can approve inspection as QA Chemist'), ('can_approve_as_qam', 'Can approve inspection as QA Manager'), ('can_reject_inspection', 'Can reject inspection')]},
        ),
    ]
