# Generated by Django 6.0.1 on 2026-02-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0007_add_custom_permissions'),
        ('raw_material_gatein', '0003_alter_poreceipt_vehicle_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialarrivalslip',
            name='vehicle_entry',
        ),
        migrations.RemoveField(
            model_name='rawmaterialinspection',
            name='po_item_receipt',
        ),
        migrations.AddField(
            model_name='materialarrivalslip',
            name='po_item_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_slip', to='raw_material_gatein.poitemreceipt'),
        ),
        migrations.AddField(
            model_name='rawmaterialinspection',
            name='arrival_slip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='quality_control.materialarrivalslip'),
        ),
    ]
