# Generated by Django 6.0.1 on 2026-02-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0008_refactor_arrival_slip_to_po_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QCInspection',
        ),
    ]
