# Generated by Django 6.0.1 on 2026-02-06 11:22

from django.db import migrations


# Group 1: qc_store - Store personnel who handle arrival slips + view inspections
QC_STORE_PERMISSIONS = [
    "can_create_arrival_slip",
    "can_edit_arrival_slip",
    "can_submit_arrival_slip",
    "can_view_arrival_slip",
    "can_view_inspection",
]

# Group 2: qc_chemist - QA Chemists who handle inspections + approve as chemist
QC_CHEMIST_PERMISSIONS = [
    "can_view_arrival_slip",
    "can_create_inspection",
    "can_edit_inspection",
    "can_submit_inspection",
    "can_view_inspection",
    "can_approve_as_chemist",
]

# Group 3: qc_manager - QA Manager with all permissions
QC_MANAGER_PERMISSIONS = [
    "can_create_arrival_slip",
    "can_edit_arrival_slip",
    "can_submit_arrival_slip",
    "can_view_arrival_slip",
    "can_create_inspection",
    "can_edit_inspection",
    "can_submit_inspection",
    "can_view_inspection",
    "can_approve_as_chemist",
    "can_approve_as_qam",
    "can_reject_inspection",
    "can_manage_material_types",
    "can_manage_qc_parameters",
]


def create_quality_control_groups(apps, schema_editor):
    """Create 3 quality_control groups: qc_store, qc_chemist, qc_manager."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups_config = {
        "qc_store": QC_STORE_PERMISSIONS,
        "qc_chemist": QC_CHEMIST_PERMISSIONS,
        "qc_manager": QC_MANAGER_PERMISSIONS,
    }

    for group_name, perm_codenames in groups_config.items():
        group, created = Group.objects.get_or_create(name=group_name)
        permissions = Permission.objects.filter(
            content_type__app_label='quality_control',
            codename__in=perm_codenames,
        )
        group.permissions.set(permissions)


def remove_quality_control_groups(apps, schema_editor):
    """Remove quality_control groups."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=["qc_store", "qc_chemist", "qc_manager"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0009_remove_qcinspection'),
    ]

    operations = [
        migrations.RunPython(create_quality_control_groups, remove_quality_control_groups),
    ]
