# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0010_create_quality_control_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialarrivalslip',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_arrival_slip', 'Can submit arrival slip to QA')]},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinspection',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_inspection', 'Can submit inspection for approval'), ('can_approve_as_chemist', 'Can approve inspection as QA Chemist'), ('can_approve_as_qam', 'Can approve inspection as QA Manager'), ('can_reject_inspection', 'Can reject inspection')]},
        ),
    ]
