# Generated by Django 6.0.1 on 2026-02-06 12:50

from django.db import migrations

STALE_PERMISSIONS = [
    "can_create_arrival_slip",
    "can_edit_arrival_slip",
    "can_view_arrival_slip",
    "can_create_inspection",
    "can_edit_inspection",
    "can_view_inspection",
]


def cleanup_stale_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        content_type__app_label='quality_control',
        codename__in=STALE_PERMISSIONS,
    ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0012_update_quality_control_groups'),
    ]

    operations = [
        migrations.RunPython(cleanup_stale_permissions, noop),
    ]
