# Generated by Django 6.0.1 on 2026-02-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0014_add_rejection_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalSlipAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='arrival_slip_attachments/')),
                ('attachment_type', models.CharField(choices=[('CERTIFICATE_OF_ANALYSIS', 'Certificate of Analysis'), ('CERTIFICATE_OF_QUANTITY', 'Certificate of Quantity')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality_control.materialarrivalslip')),
            ],
            options={
                'unique_together': {('arrival_slip', 'attachment_type')},
            },
        ),
    ]
