# Generated by Django 6.0.1 on 2026-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0015_arrivalslipattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialinspection',
            name='internal_report_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rawmaterialinspection',
            name='purchase_order_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterialinspection',
            name='supplier_batch_lot_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
