# Generated by Django 6.0.1 on 2026-02-25 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0016_make_po_lot_optional_add_internal_report_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialarrivalslip',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_arrival_slip', 'Can submit arrival slip to QA'), ('can_send_back_arrival_slip', 'Can send arrival slip back to gate for correction')]},
        ),
        migrations.AddField(
            model_name='materialarrivalslip',
            name='sent_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialarrivalslip',
            name='sent_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_back_arrival_slips', to=settings.AUTH_USER_MODEL),
        ),
    ]
