# Generated by Django 6.0.1 on 2026-02-25 11:31

from django.db import migrations


def add_send_back_perm_to_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    perm = Permission.objects.filter(
        content_type__app_label='quality_control',
        codename='can_send_back_arrival_slip',
    ).first()
    if not perm:
        return

    # Grant to qc_store (gate people who view QC) and qc_chemist
    for group_name in ('qc_store', 'qc_chemist', 'qc_manager'):
        try:
            group = Group.objects.get(name=group_name)
            group.permissions.add(perm)
        except Group.DoesNotExist:
            pass


def reverse_perm(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    perm = Permission.objects.filter(
        content_type__app_label='quality_control',
        codename='can_send_back_arrival_slip',
    ).first()
    if not perm:
        return

    for group_name in ('qc_store', 'qc_chemist', 'qc_manager'):
        try:
            group = Group.objects.get(name=group_name)
            group.permissions.remove(perm)
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0017_add_send_back_fields_and_permission'),
    ]

    operations = [
        migrations.RunPython(add_send_back_perm_to_groups, reverse_perm),
    ]
