# Generated by Django 6.0.1 on 2026-01-23 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_management', '0004_vehicleentry_entry_type_alter_vehicleentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNeedGateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(choices=[('CANTEEN', 'Canteen'), ('OFFICE', 'Office'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=20)),
                ('supplier_name', models.CharField(max_length=200)),
                ('material_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LTR', 'Litre'), ('BOX', 'Box')], max_length=10)),
                ('receiving_department', models.CharField(max_length=100)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_challan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('canteen_supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_or_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_need_entries', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_need_entry', to='driver_management.vehicleentry')),
            ],
        ),
    ]
