# Generated by Django 6.0.1 on 2026-01-23 06:06

from decimal import Decimal

import daily_needs_gatein.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0001_initial'),
        ('driver_management', '0004_vehicleentry_entry_type_alter_vehicleentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyneedgateentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Daily Need Gate Entry', 'verbose_name_plural': 'Daily Need Gate Entries'},
        ),
        migrations.AlterField(
            model_name='dailyneedgateentry',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[daily_needs_gatein.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='dailyneedgateentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Quantity must be positive')]),
        ),
        migrations.AddIndex(
            model_name='dailyneedgateentry',
            index=models.Index(fields=['item_category'], name='daily_needs_item_ca_b9869f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyneedgateentry',
            index=models.Index(fields=['created_at'], name='daily_needs_created_dc1862_idx'),
        ),
    ]
