# Generated by Django 6.0.1 on 2026-01-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0002_add_validators_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category List',
                'verbose_name_plural': 'Category Lists',
                'ordering': ['category_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='dailyneedgateentry',
            new_name='daily_needs_item_ca_851021_idx',
            old_name='daily_needs_item_ca_b9869f_idx',
        ),
        migrations.AlterField(
            model_name='dailyneedgateentry',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_need_entries', to='daily_needs_gatein.categorylist'),
        ),
    ]
