# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department'),
        ('daily_needs_gatein', '0003_categorylist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyneedgateentry',
            name='receiving_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_need_entries', to='accounts.department'),
        ),
    ]
