# Generated by Django 6.0.1 on 2026-02-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0004_alter_dailyneedgateentry_receiving_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylist',
            options={'ordering': ['category_name'], 'permissions': [('can_view_category', 'Can view category'), ('can_manage_category', 'Can manage category')], 'verbose_name': 'Category List', 'verbose_name_plural': 'Category Lists'},
        ),
        migrations.AlterModelOptions(
            name='dailyneedgateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_daily_need_entry', 'Can create daily need gate entry'), ('can_view_daily_need_entry', 'Can view daily need gate entry'), ('can_edit_daily_need_entry', 'Can edit daily need gate entry'), ('can_delete_daily_need_entry', 'Can delete daily need gate entry'), ('can_complete_daily_need_entry', 'Can complete daily need gate entry')], 'verbose_name': 'Daily Need Gate Entry', 'verbose_name_plural': 'Daily Need Gate Entries'},
        ),
    ]
