# Generated by Django 6.0.1 on 2026-02-06 10:56

from django.db import migrations


def create_daily_needs_gatein_group(apps, schema_editor):
    """Create 'daily_needs_gatein' group with all daily_needs_gatein app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='daily_needs_gatein')

    permissions = Permission.objects.filter(
        content_type__app_label='daily_needs_gatein'
    )
    group.permissions.set(permissions)


def remove_daily_needs_gatein_group(apps, schema_editor):
    """Remove 'daily_needs_gatein' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='daily_needs_gatein').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0005_add_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(create_daily_needs_gatein_group, remove_daily_needs_gatein_group),
    ]
