# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0006_create_daily_needs_gatein_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylist',
            options={'ordering': ['category_name'], 'permissions': [('can_manage_category', 'Can manage category')], 'verbose_name': 'Category List', 'verbose_name_plural': 'Category Lists'},
        ),
        migrations.AlterModelOptions(
            name='dailyneedgateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_complete_daily_need_entry', 'Can complete daily need gate entry')], 'verbose_name': 'Daily Need Gate Entry', 'verbose_name_plural': 'Daily Need Gate Entries'},
        ),
    ]
