# Generated by Django 6.0.1 on 2026-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0009_cleanup_stale_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylist',
            options={'ordering': ['category_name'], 'permissions': [('can_manage_category', 'Can manage category')]},
        ),
        migrations.AlterModelOptions(
            name='dailyneedgateentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_complete_daily_need_entry', 'Can complete daily need gate entry')]},
        ),
    ]
