# Generated by Django 6.0.1 on 2026-02-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0010_alter_categorylist_options_and_more'),
        ('gate_core', '0004_remove_unitchoice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyneedgateentry',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_need_entries', to='gate_core.unitchoice'),
        ),
    ]
