# Generated by Django 6.0.1 on 2026-01-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userrole'),
        ),
    ]
