# Generated by Django 6.0.1 on 2026-01-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='driver_vehicle_entries', to='company.company'),
            preserve_default=False,
        ),
    ]
