# Generated by Django 6.0.1 on 2026-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0003_vehicleentry_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='entry_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('DAILY_NEED', 'Daily Need / Canteen'), ('MAINTENANCE', 'Maintenance'), ('CONSTRUCTION', 'Construction')], default='RAW_MATERIAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('QC_PENDING', 'QC Pending'), ('QC_COMPLETED', 'QC Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
