# Generated by Django 6.0.1 on 2026-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0004_vehicleentry_entry_type_alter_vehicleentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SECURITY_CHECK_DONE', 'Security Check Done'), ('ARRIVAL_SLIP_SUBMITTED', 'Arrival Slip Submitted'), ('ARRIVAL_SLIP_REJECTED', 'Arrival Slip Rejected'), ('IN_PROGRESS', 'In Progress'), ('QC_PENDING', 'QC Pending'), ('QC_IN_REVIEW', 'QC In Review'), ('QC_AWAITING_QAM', 'Awaiting QAM Approval'), ('QC_COMPLETED', 'QC Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
