# Generated by Django 6.0.1 on 2026-01-17 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POItemReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('po_item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('ordered_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('accepted_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('rejected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('short_qty', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('uom', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('po_number', models.CharField(max_length=30)),
                ('supplier_code', models.CharField(max_length=30)),
                ('supplier_name', models.CharField(max_length=150)),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
