# Generated by Django 6.0.1 on 2026-01-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material_gatein', '0001_initial'),
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poreceipt',
            name='vehicle_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_receipts', to='vehicle_management.vehicleentry'),
        ),
        migrations.AddField(
            model_name='poitemreceipt',
            name='po_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='raw_material_gatein.poreceipt'),
        ),
        migrations.AlterUniqueTogether(
            name='poreceipt',
            unique_together={('vehicle_entry', 'po_number')},
        ),
        migrations.AlterUniqueTogether(
            name='poitemreceipt',
            unique_together={('po_receipt', 'po_item_code')},
        ),
    ]
