# Generated by Django 6.0.1 on 2026-01-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0002_initial'),
        ('raw_material_gatein', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poreceipt',
            name='vehicle_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_receipts', to='driver_management.vehicleentry'),
        ),
    ]
