# Generated by Django 6.0.1 on 2026-02-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0003_alter_poreceipt_vehicle_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poreceipt',
            options={'permissions': [('can_create_raw_material_entry', 'Can create raw material gate entry'), ('can_view_raw_material_entry', 'Can view raw material gate entry'), ('can_edit_raw_material_entry', 'Can edit raw material gate entry'), ('can_delete_raw_material_entry', 'Can delete raw material gate entry'), ('can_complete_raw_material_entry', 'Can complete raw material gate entry'), ('can_receive_po', 'Can receive PO items'), ('can_view_po_receipt', 'Can view PO receipts'), ('can_edit_po_receipt', 'Can edit PO receipts'), ('can_delete_po_receipt', 'Can delete PO receipts')]},
        ),
    ]
