# Generated by Django 6.0.1 on 2026-02-06 10:37

from django.db import migrations


def create_raw_material_gatein_group(apps, schema_editor):
    """Create 'raw_material_gatein' group with all raw_material_gatein app permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='raw_material_gatein')

    permissions = Permission.objects.filter(
        content_type__app_label='raw_material_gatein'
    )
    group.permissions.set(permissions)


def remove_raw_material_gatein_group(apps, schema_editor):
    """Remove 'raw_material_gatein' group."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='raw_material_gatein').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0004_add_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(create_raw_material_gatein_group, remove_raw_material_gatein_group),
    ]
