# Generated by Django 6.0.1 on 2026-02-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0005_create_raw_material_gatein_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poreceipt',
            options={'permissions': [('can_complete_raw_material_entry', 'Can complete raw material gate entry'), ('can_receive_po', 'Can receive PO items')]},
        ),
    ]
