# Generated by Django 6.0.1 on 2026-02-06 12:50

from django.db import migrations

STALE_PERMISSIONS = [
    "can_create_raw_material_entry",
    "can_view_raw_material_entry",
    "can_edit_raw_material_entry",
    "can_delete_raw_material_entry",
    "can_view_po_receipt",
    "can_edit_po_receipt",
    "can_delete_po_receipt",
]


def cleanup_stale_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        content_type__app_label='raw_material_gatein',
        codename__in=STALE_PERMISSIONS,
    ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0007_update_raw_material_gatein_group'),
    ]

    operations = [
        migrations.RunPython(cleanup_stale_permissions, noop),
    ]
