# Generated by Django 6.0.1 on 2026-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0008_cleanup_stale_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitemreceipt',
            name='sap_line_num',
            field=models.IntegerField(blank=True, help_text='SAP PO LineNum (from POR1) - used as BaseLine in GRPO', null=True),
        ),
        migrations.AddField(
            model_name='poreceipt',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, help_text='SAP PO DocEntry (from OPOR) - used as BaseEntry in GRPO', null=True),
        ),
    ]
