# Generated by Django 6.0.1 on 2026-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0009_add_sap_po_linking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitemreceipt',
            name='gl_account',
            field=models.CharField(blank=True, default='', help_text='G/L Account from PO (POR1.AcctCode)', max_length=30),
        ),
        migrations.AddField(
            model_name='poitemreceipt',
            name='tax_code',
            field=models.CharField(blank=True, default='', help_text='Tax code from PO (POR1.TaxCode)', max_length=20),
        ),
        migrations.AddField(
            model_name='poitemreceipt',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Unit price from PO (POR1.Price)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='poitemreceipt',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', help_text='Warehouse code from PO (POR1.WhsCode)', max_length=20),
        ),
        migrations.AddField(
            model_name='poreceipt',
            name='branch_id',
            field=models.IntegerField(blank=True, help_text='SAP Branch/Business Place ID (OPOR.BPLId)', null=True),
        ),
        migrations.AddField(
            model_name='poreceipt',
            name='vendor_ref',
            field=models.CharField(blank=True, default='', help_text='Vendor reference from PO (OPOR.NumAtCard)', max_length=100),
        ),
    ]
