# Generated by Django 6.0.1 on 2026-02-07 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web Browser'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='WEB', max_length=20)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('GATE_ENTRY_CREATED', 'Gate Entry Created'), ('GATE_ENTRY_STATUS_CHANGED', 'Gate Entry Status Changed'), ('SECURITY_CHECK_DONE', 'Security Check Completed'), ('WEIGHMENT_RECORDED', 'Weighment Recorded'), ('ARRIVAL_SLIP_SUBMITTED', 'Arrival Slip Submitted'), ('QC_INSPECTION_SUBMITTED', 'QC Inspection Submitted'), ('QC_CHEMIST_APPROVED', 'QC Chemist Approved'), ('QC_QAM_APPROVED', 'QC QAM Approved'), ('QC_REJECTED', 'QC Rejected'), ('QC_COMPLETED', 'QC Completed'), ('GRPO_POSTED', 'GRPO Posted to SAP'), ('GRPO_FAILED', 'GRPO Posting Failed'), ('GENERAL_ANNOUNCEMENT', 'General Announcement')], default='GENERAL_ANNOUNCEMENT', max_length=50)),
                ('click_action_url', models.CharField(blank=True, help_text='Frontend route to navigate to on click', max_length=500)),
                ('reference_type', models.CharField(blank=True, help_text='Entity type: vehicle_entry, inspection, grpo_posting, etc.', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the referenced entity', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_send_notification', 'Can send manual notifications'), ('can_send_bulk_notification', 'Can send bulk/broadcast notifications')],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
