# Generated by Django 6.0.1 on 2026-02-07 10:06

from django.db import migrations


def create_notification_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct = ContentType.objects.get(app_label="notifications", model="notification")

    group, _ = Group.objects.get_or_create(name="Notification Sender")

    perms = Permission.objects.filter(
        content_type=ct,
        codename__in=[
            "can_send_notification",
            "can_send_bulk_notification",
        ]
    )
    group.permissions.set(perms)


def reverse(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Notification Sender").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_notification_groups, reverse),
    ]
