# Generated by Django 6.0.1 on 2026-02-03 06:19

from django.db import migrations


NOTIFICATION_TYPES = [
    # Person Gate Events
    {
        "code": "PERSON_ENTRY",
        "name": "Person Entry",
        "description": "Notification when a visitor or labour enters the facility",
        "title_template": "New Entry: {person_name}",
        "body_template": "{person_type} {person_name} entered via {gate}",
        "target_roles": ["Admin", "Security"],
    },
    {
        "code": "PERSON_EXIT",
        "name": "Person Exit",
        "description": "Notification when a visitor or labour exits the facility",
        "title_template": "Exit: {person_name}",
        "body_template": "{person_name} has exited the facility",
        "target_roles": ["Admin", "Security"],
    },
    {
        "code": "LONG_DURATION_ALERT",
        "name": "Long Duration Alert",
        "description": "Alert when a person has been inside for too long (>8 hours)",
        "title_template": "Long Duration Alert",
        "body_template": "{person_name} has been inside for {duration}",
        "target_roles": ["Admin"],
    },
    {
        "code": "BLACKLISTED_PERSON",
        "name": "Blacklisted Person Alert",
        "description": "Alert when a blacklisted person attempts entry",
        "title_template": "Blacklisted Person Alert",
        "body_template": "Blacklisted person {person_name} attempted entry at {gate}",
        "target_roles": ["Admin", "Security"],
    },
    # Vehicle Gate Events
    {
        "code": "VEHICLE_ENTRY",
        "name": "Vehicle Entry",
        "description": "Notification when a vehicle enters the facility",
        "title_template": "Vehicle Entry: {vehicle_number}",
        "body_template": "Vehicle {vehicle_number} entered via {gate}",
        "target_roles": ["Admin", "Store"],
    },
    {
        "code": "VEHICLE_EXIT",
        "name": "Vehicle Exit",
        "description": "Notification when a vehicle exits the facility",
        "title_template": "Vehicle Exit: {vehicle_number}",
        "body_template": "Vehicle {vehicle_number} has exited the facility",
        "target_roles": ["Admin", "Store"],
    },
    # Material Gate Events
    {
        "code": "RAW_MATERIAL_GATEIN",
        "name": "Raw Material Gate-In",
        "description": "Notification when raw material is received",
        "title_template": "Raw Material Received",
        "body_template": "Raw material received via vehicle {vehicle_number}",
        "target_roles": ["Store", "QC"],
    },
    {
        "code": "DAILY_NEEDS_GATEIN",
        "name": "Daily Needs Gate-In",
        "description": "Notification when daily supplies are received",
        "title_template": "Daily Supplies Received",
        "body_template": "Daily supplies received via vehicle {vehicle_number}",
        "target_roles": ["Store"],
    },
    {
        "code": "MAINTENANCE_GATEIN",
        "name": "Maintenance Gate-In",
        "description": "Notification when maintenance material is received",
        "title_template": "Maintenance Material Received",
        "body_template": "Maintenance material received via vehicle {vehicle_number}",
        "target_roles": ["Store"],
    },
    {
        "code": "CONSTRUCTION_GATEIN",
        "name": "Construction Gate-In",
        "description": "Notification when construction material is received",
        "title_template": "Construction Material Received",
        "body_template": "Construction material received via vehicle {vehicle_number}",
        "target_roles": ["Store"],
    },
    # QC Events
    {
        "code": "QC_PENDING",
        "name": "QC Pending",
        "description": "Notification when QC inspection is needed",
        "title_template": "QC Inspection Needed",
        "body_template": "QC inspection required for vehicle {vehicle_number}",
        "target_roles": ["QC"],
    },
    {
        "code": "QC_COMPLETED",
        "name": "QC Completed",
        "description": "Notification when QC is approved",
        "title_template": "QC Approved",
        "body_template": "QC approved for vehicle {vehicle_number}",
        "target_roles": ["Admin", "Store"],
    },
    {
        "code": "QC_FAILED",
        "name": "QC Failed",
        "description": "Notification when QC is rejected",
        "title_template": "QC Rejected",
        "body_template": "QC rejected for vehicle {vehicle_number}",
        "target_roles": ["Admin", "Store", "QC"],
    },
    # Weighment Events
    {
        "code": "WEIGHMENT_COMPLETED",
        "name": "Weighment Completed",
        "description": "Notification when weighment is completed",
        "title_template": "Weighment Completed",
        "body_template": "Weighment completed for vehicle {vehicle_number}",
        "target_roles": ["Store"],
    },
    # Security Alerts
    {
        "code": "SECURITY_ALERT",
        "name": "Security Alert",
        "description": "General security alert",
        "title_template": "Security Alert",
        "body_template": "{alert_message}",
        "target_roles": ["Admin", "Security"],
    },
]


def create_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("notifications", "NotificationType")
    UserRole = apps.get_model("company", "UserRole")

    for nt_data in NOTIFICATION_TYPES:
        target_role_names = nt_data.pop("target_roles")

        # Create notification type
        notification_type, created = NotificationType.objects.get_or_create(
            code=nt_data["code"],
            defaults=nt_data
        )

        # Add target roles if they exist
        if created:
            for role_name in target_role_names:
                try:
                    role = UserRole.objects.get(name=role_name)
                    notification_type.target_roles.add(role)
                except UserRole.DoesNotExist:
                    pass  # Role doesn't exist yet, skip


def remove_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("notifications", "NotificationType")
    codes = [nt["code"] for nt in NOTIFICATION_TYPES]
    NotificationType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_notification_types, remove_notification_types),
    ]
