# Generated by Django 6.0.1 on 2026-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_create_notification_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GATE_ENTRY_CREATED', 'Gate Entry Created'), ('GATE_ENTRY_STATUS_CHANGED', 'Gate Entry Status Changed'), ('SECURITY_CHECK_DONE', 'Security Check Completed'), ('WEIGHMENT_RECORDED', 'Weighment Recorded'), ('ARRIVAL_SLIP_SUBMITTED', 'Arrival Slip Submitted'), ('QC_INSPECTION_SUBMITTED', 'QC Inspection Submitted'), ('QC_CHEMIST_APPROVED', 'QC Chemist Approved'), ('QC_QAM_APPROVED', 'QC QAM Approved'), ('QC_REJECTED', 'QC Rejected'), ('QC_COMPLETED', 'QC Completed'), ('PO_RECEIVED', 'PO Items Received'), ('GATE_ENTRY_COMPLETED', 'Gate Entry Completed'), ('GRPO_POSTED', 'GRPO Posted to SAP'), ('GRPO_FAILED', 'GRPO Posting Failed'), ('GENERAL_ANNOUNCEMENT', 'General Announcement')], default='GENERAL_ANNOUNCEMENT', max_length=50),
        ),
    ]
