# Generated by Django 6.0.1 on 2026-02-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_notification_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='target_roles',
        ),
    ]
