# Generated by Django 6.0.1 on 2026-01-17 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_weight', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('weighbridge_slip_no', models.CharField(blank=True, max_length=50)),
                ('first_weighment_time', models.DateTimeField(blank=True, null=True)),
                ('second_weighment_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weighment', to='vehicle_management.vehicleentry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
