# Generated by Django 6.0.1 on 2026-02-06 11:00

from django.db import migrations


def create_permissions_and_group(apps, schema_editor):
    """
    Create custom permissions and group for gate_core.
    Since gate_core only has abstract models, permissions are created manually
    using the ContentType for the gate_core app.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    # Create a content type for gate_core permissions
    ct, _ = ContentType.objects.get_or_create(
        app_label='gate_core',
        model='gatecore',
    )

    # Define custom permissions
    custom_permissions = [
        ("can_view_raw_material_full_entry", "Can view full raw material gate entry"),
        ("can_view_daily_need_full_entry", "Can view full daily need gate entry"),
        ("can_view_maintenance_full_entry", "Can view full maintenance gate entry"),
        ("can_view_construction_full_entry", "Can view full construction gate entry"),
    ]

    permission_objects = []
    for codename, name in custom_permissions:
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            content_type=ct,
            defaults={'name': name}
        )
        permission_objects.append(perm)

    # Create group with all permissions
    group, _ = Group.objects.get_or_create(name='gate_core')
    group.permissions.set(permission_objects)


def remove_permissions_and_group(apps, schema_editor):
    """Remove custom permissions and group for gate_core."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(name='gate_core').delete()

    try:
        ct = ContentType.objects.get(app_label='gate_core', model='gatecore')
        Permission.objects.filter(content_type=ct).delete()
        ct.delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(create_permissions_and_group, remove_permissions_and_group),
    ]
