# Generated by Django 6.0.1 on 2026-02-06 11:02

from django.db import migrations


def add_can_view_gate_entry(apps, schema_editor):
    """Add can_view_gate_entry permission and update gate_core group."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    ct = ContentType.objects.get(app_label='gate_core', model='gatecore')

    perm, _ = Permission.objects.get_or_create(
        codename='can_view_gate_entry',
        content_type=ct,
        defaults={'name': 'Can view gate entry'}
    )

    # Add to existing group
    try:
        group = Group.objects.get(name='gate_core')
        group.permissions.add(perm)
    except Group.DoesNotExist:
        pass


def remove_can_view_gate_entry(apps, schema_editor):
    """Remove can_view_gate_entry permission."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    try:
        ct = ContentType.objects.get(app_label='gate_core', model='gatecore')
        Permission.objects.filter(codename='can_view_gate_entry', content_type=ct).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0001_add_custom_permissions_and_group'),
    ]

    operations = [
        migrations.RunPython(add_can_view_gate_entry, remove_can_view_gate_entry),
    ]
