# Generated by Django 6.0.1 on 2026-02-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitchoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unitchoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unitchoice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='unitchoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unitchoice',
            name='updated_by',
        ),
    ]
