# Generated by Django 6.0.1 on 2026-02-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0005_increase_status_max_length'),
        ('gate_core', '0004_remove_unitchoice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gate_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gate_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='driver_management.vehicleentry')),
            ],
        ),
    ]
